baseURL = "www.example.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "Thamani Economics Consulting"
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[[menu.main]]
name = "Team"
url = "/team/"
weight = 2
[params]
google_analytics_id = "UA-103684160-2"
google_tag_manager_id = "GTM-T9HGLVM"
[params.homepage_meta_tags]
meta_description = "TEC Main Website"
meta_og_description = "Thamani Economics Consulting - Delivering Value Consulting"
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "Thamani Economics Consulting"
meta_og_type = "website"
meta_og_url = ""
meta_twitter_card = "summary"
meta_twitter_creator = "@thamani_econ"
meta_twitter_site = "@thamanieconomics"
[params.logo]
alt = "Thamani Economics Consulting"
mobile = "/images/Thamani Economics Consulting-01.png"
standard = "/images/Thamani Economics Consulting-01.png"
