baseURL = "www.example.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "Thamani Economics Consulting"
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[[menu.main]]
name = "Team"
url = "/team/"
weight = 2
[params]
google_analytics_id = "UA-103684160-2"
google_tag_manager_id = "GTM-T9HGLVM"
[params.homepage_meta_tags]
meta_description = "TEC Main Website"
meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "Thamani Economics Consulting"
meta_og_type = "website"
meta_og_url = "https://hugo-serif.netlify.com"
meta_twitter_card = "summary"
meta_twitter_creator = ""
meta_twitter_site = "@thamanieconomics"
[params.logo]
alt = "Serif - A Hugo Business Theme"
mobile = "images/logo-mobile.svg"
standard = "/images/Thamani Economics Consulting_cmyk-01.jpg"
